# Generated by Django 4.0.3 on 2022-03-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(max_length=60)),
                ('Duration', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
    ]
